version: 2

models:
  - name: stg_power_generation
    columns:
      - name: dtm_power_generation
        data_tests:
          - not_null

      - name: id_ons_plant
        data_tests:
          - not_null

  - name: stg_production_plants
    columns:
      - name: id_ons_plant
        data_tests:
          - not_null

      - name: id_aneel_generation_enterprise
        data_tests:
          - not_null

      - name: dsc_plant_name
        data_tests:
          - not_null