version: 2

models:
  - name: stg_power_generation
    columns:
      - name: cod_generation_entity_key
        data_tests:
          - not_null
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          arguments: # available in v1.10.5 and higher. Older versions can set the <argument_name> as the top-level property.
            combination_of_columns:
              - cod_generation_entity_key
              - dtm_power_generation

  - name: stg_production_plants
    columns:
      - name: cod_plant_entity_key
        data_tests:
          - not_null

      - name: dsc_plant_name
        data_tests:
          - not_null